/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_MoteurDeRecherche */

#ifndef _Included_model_MoteurDeRecherche
#define _Included_model_MoteurDeRecherche
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_MoteurDeRecherche
 * Method:    indexationTexte
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_model_MoteurDeRecherche_indexationTexte
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
