/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_MoteurDeRecherche */

#ifndef _Included_model_MoteurDeRecherche
#define _Included_model_MoteurDeRecherche
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_MoteurDeRecherche
 * Method:    indexationTexte
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_model_MoteurDeRecherche_indexationTexte
  (JNIEnv *, jclass);

/*
 * Class:     model_MoteurDeRecherche
 * Method:    rechercheParMotCle
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_model_MoteurDeRecherche_rechercheParMotCle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     model_MoteurDeRecherche
 * Method:    rechercheTexteParFichier
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_model_MoteurDeRecherche_rechercheTexteParFichier
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
